version: "3.8"
services:

  postgres:
    image: pgvector/pgvector:pg16 
    command: >
      postgres
      -c max_connections=500
      -c shared_buffers=512MB

    volumes:
      - pgvector:/var/lib/postgresql/data

    networks:
      - ${NETWORK}

    ## Descomente as linhas abaixo para uso externo
    #ports:
    #  - 5432:5432

    environment:
      ## Senha do postgres 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      ## Timezone
      - TZ=UTC

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  pgvector:
    external: true
    name: pgvector

networks:
  ${NETWORK}: 
    external: true
    name: ${NETWORK} 