version: "3.7"
services:

  chatwoot_app:
    image: ghcr.io/fazer-ai/chatwoot:latest 
    command: >
      sh -c "echo 'Rails.application.config.active_storage.variant_processor = :mini_magick' > /app/config/initializers/active_storage.rb && bundle exec rails s -p 3000 -b 0.0.0.0"
    entrypoint: docker/entrypoints/rails.sh

    volumes:
      - chatwoot_storage:/app/storage 
      - chatwoot_public:/app/public 
      - chatwoot_mailer:/app/app/views/devise/mailer 
      - chatwoot_mailers:/app/app/views/mailers 

    networks:
      - ${NETWORK}
    
    environment:
      ## üåê Qualquer Url com # no final
      #- CHATWOOT_HUB_URL=https://oriondesign.art.br/setup#

      ## üè¢ Nome da Empresa
      - INSTALLATION_NAME=${NOMBRE_EMPRESA}

      ## üîê Secret key
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}

      ## üí¨ Url Chatwoot
      - FRONTEND_URL=${URL_CHATWOOT}
      - FORCE_SSL=true

      ## üåç Idioma/Localiza√ß√£o padr√£o
      - DEFAULT_LOCALE=es_CO
      - TZ=UTC

      ## ‚òÅÔ∏è Google Cloud - Modifique de acordo com os seus dados
      #- GOOGLE_OAUTH_CLIENT_ID=369777777777-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
      #- GOOGLE_OAUTH_CLIENT_SECRET=ABCDEF-GHijklmnoPqrstuvwX-yz1234567
      #- GOOGLE_OAUTH_CALLBACK_URL=https://<your-server-domain>/omniauth/google_oauth2/callback

      ## üßë‚Äçüíª Dados do Redis
      - REDIS_URL=redis://chatwoot_redis:6379

      ## üóÑÔ∏è Dados do Postgres
      - POSTGRES_HOST=pgvector
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} ## Senha do postgres
      - POSTGRES_DATABASE=chatwoot

      ## üè† Armazenamento
      - ACTIVE_STORAGE_SERVICE=local ## use s3_compatible para MinIO
      #- STORAGE_BUCKET_NAME=chatwoot
      #- STORAGE_ACCESS_KEY_ID=ACCESS_KEY_MINIO
      #- STORAGE_SECRET_ACCESS_KEY=SECRET_KEY_MINIO
      #- STORAGE_REGION=eu-south
      #- STORAGE_ENDPOINT=https://s3.DOMINIO.COM
      #- STORAGE_FORCE_PATH_STYLE=true

      ## üìß Dados do SMTP
      - MAILER_SENDER_EMAIL=${EMAIL} <${EMAIL}> ## Email SMTP
      - SMTP_DOMAIN=${DOMINIO_EMAIL} ## Dominio do email
      - SMTP_ADDRESS=${SMTP_ADDRESS} ## Host SMTP
      - SMTP_PORT=${PORT} ## Porta SMTP
      - SMTP_SSL=${SSL} ## Se a porta for 465 = true | Se a porta for 587 = false
      - SMTP_USERNAME=${USUARIO} ## Usuario SMTP
      - SMTP_PASSWORD=${SMTP_PASSWORD} ## Senha do SMTP
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=${EMAIL} ## Email SMTP

      ## ‚öôÔ∏è Melhorias
      - SIDEKIQ_CONCURRENCY=10
      - RACK_TIMEOUT_SERVICE_TIMEOUT=0
      - RAILS_MAX_THREADS=5
      - WEB_CONCURRENCY=2
      - ENABLE_RACK_ATTACK=false
      - RAILS_TIME_ZONE=UTC

      ## ‚ö° Outras configura√ß√µes
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - ENABLE_ACCOUNT_SIGNUP=false

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.chatwoot_app.rule=Host(`${URL_CHATWOOT}`)
        - traefik.http.routers.chatwoot_app.entrypoints=websecure
        - traefik.http.routers.chatwoot_app.tls.certresolver=letsencryptresolver
        - traefik.http.routers.chatwoot_app.priority=1
        - traefik.http.routers.chatwoot_app.service=chatwoot_app
        - traefik.http.services.chatwoot_app.loadbalancer.server.port=3000
        - traefik.http.services.chatwoot_app.loadbalancer.passHostHeader=true
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.chatwoot_app.middlewares=sslheader


  chatwoot_sidekiq:
    image: ghcr.io/fazer-ai/chatwoot:latest
 ## Vers√£o do Chatwoot
    command: bundle exec sidekiq -C config/sidekiq.yml

    volumes:
      - chatwoot_storage:/app/storage ## Arquivos de conversa
      - chatwoot_public:/app/public ## Arquivos de logos
      - chatwoot_mailer:/app/app/views/devise/mailer ## Arquivos de email
      - chatwoot_mailers:/app/app/views/mailers ## Arquivos de emails

    networks:
      - ${NETWORK} ## Nome da rede interna

    environment:
      ## üåê Qualquer Url com # no final
      #- CHATWOOT_HUB_URL=https://oriondesign.art.br/setup#

      ## üè¢ Nome da Empresa
      - INSTALLATION_NAME=${NOMBRE_EMPRESA}

      ## üîê Secret key
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}

      ## üí¨ Url Chatwoot
      - FRONTEND_URL=${URL_CHATWOOT}
      - FORCE_SSL=true

      ## üåç Idioma/Localiza√ß√£o padr√£o
      - DEFAULT_LOCALE=es_CO
      - TZ=UTC

      ## ‚òÅÔ∏è Google Cloud - Modifique de acordo com os seus dados
      #- GOOGLE_OAUTH_CLIENT_ID=369777777777-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
      #- GOOGLE_OAUTH_CLIENT_SECRET=ABCDEF-GHijklmnoPqrstuvwX-yz1234567
      #- GOOGLE_OAUTH_CALLBACK_URL=https://<your-server-domain>/omniauth/google_oauth2/callback

      ## üßë‚Äçüíª Dados do Redis
      - REDIS_URL=redis://chatwoot_redis:6379

      ## üóÑÔ∏è Dados do Postgres
      - POSTGRES_HOST=pgvector
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} ## Senha do postgres
      - POSTGRES_DATABASE=chatwoot

      ## üè† Armazenamento
      - ACTIVE_STORAGE_SERVICE=local ## use s3_compatible para MinIO
      #- STORAGE_BUCKET_NAME=chatwoot
      #- STORAGE_ACCESS_KEY_ID=ACCESS_KEY_MINIO
      #- STORAGE_SECRET_ACCESS_KEY=SECRET_KEY_MINIO
      #- STORAGE_REGION=eu-south
      #- STORAGE_ENDPOINT=https://s3.DOMINIO.COM
      #- STORAGE_FORCE_PATH_STYLE=true

      ## üìß Dados do SMTP
      - MAILER_SENDER_EMAIL=${EMAIL} <${EMAIL}> ## Email SMTP
      - SMTP_DOMAIN=${DOMINIO_EMAIL} ## Dominio do email
      - SMTP_ADDRESS=${SMTP_ADDRESS} ## Host SMTP
      - SMTP_PORT=${PORT} ## Porta SMTP
      - SMTP_SSL=${SSL} ## Se a porta for 465 = true | Se a porta for 587 = false
      - SMTP_USERNAME=${USUARIO} ## Usuario SMTP
      - SMTP_PASSWORD=${SMTP_PASSWORD} ## Senha do SMTP
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_OPENSSL_VERIFY_MODE=peer
      - MAILER_INBOUND_EMAIL_DOMAIN=${EMAIL} ## Email SMTP

      ## ‚öôÔ∏è Melhorias
      - SIDEKIQ_CONCURRENCY=10
      - RACK_TIMEOUT_SERVICE_TIMEOUT=0
      - RAILS_MAX_THREADS=5
      - WEB_CONCURRENCY=2
      - ENABLE_RACK_ATTACK=false
      - RAILS_TIME_ZONE=UTC

      ## ‚ö° Outras configura√ß√µes
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - RAILS_LOG_TO_STDOUT=true
      - USE_INBOX_AVATAR_FOR_BOT=true
      - ENABLE_ACCOUNT_SIGNUP=false

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M


  chatwoot_redis:
    image: redis:latest  ## Vers√£o do Redis
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "6379"
      ]

    volumes:
      - chatwoot_redis:/data

    networks:
      - ${NETWORK} ## Nome da rede interna

    ## Descomente as linhas abaixo para uso externo
    #ports:
    #  - 6379:6379

    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M


volumes:
  chatwoot_storage:
    external: true
    name: chatwoot_storage
  chatwoot_public:
    external: true
    name: chatwoot_public
  chatwoot_mailer:
    external: true
    name: chatwoot_mailer
  chatwoot_mailers:
    external: true
    name: chatwoot_mailers
  volumes:
  chatwoot_redis:
    external: true
    name: chatwoot_redis

networks:
  ${NETWORK}: ## Nome da rede interna
    external: true
    name: ${NETWORK} ## Nome da rede interna
